import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/auth";
import { Octokit } from "octokit";
import { ActionsGenerator } from "../../../../src/github/actions";

export const runtime = "nodejs";

export async function POST(request: NextRequest) {
  try {
    const session = (await auth()) as { accessToken?: string } | null;

    if (!session || !session.accessToken) {
      return NextResponse.json(
        { success: false, error: "Unauthorized. Please sign in with GitHub." },
        { status: 401 }
      );
    }

    const { markdown, setupAction, frequency, profileData } = await request.json();

    if (!markdown) {
      return NextResponse.json(
        { success: false, error: "Markdown content is required" },
        { status: 400 }
      );
    }

    const octokit = new Octokit({ auth: session.accessToken });
    const { data: user } = await octokit.rest.users.getAuthenticated();
    const username = user.login;
    const repoName = username;

    // 1. Ensure profile repository exists
    try {
      await octokit.rest.repos.get({ owner: username, repo: repoName });
    } catch (error) {
      const err = error as { status?: number };
      if (err.status === 404) {
        await octokit.rest.repos.createForAuthenticatedUser({
          name: repoName,
          description: `${username}'s GitHub Profile (Generated by ProfileAgent)`,
          auto_init: true,
          private: false,
        });
        // Wait a bit for GitHub to initialize the repo
        await new Promise((resolve) => setTimeout(resolve, 2000));
      } else {
        throw error;
      }
    }

    // 2. Push README.md
    let sha: string | undefined;
    try {
      const { data: currentFile } = await octokit.rest.repos.getContent({
        owner: username,
        repo: repoName,
        path: "README.md",
      });
      if (!Array.isArray(currentFile)) {
        sha = currentFile.sha;
      }
    } catch (e) {
      // File doesn't exist, that's fine
    }

    await octokit.rest.repos.createOrUpdateFileContents({
      owner: username,
      repo: repoName,
      path: "README.md",
      message: "📊 Update GitHub Profile README [skip ci]",
      content: Buffer.from(markdown).toString("base64"),
      sha,
    });

    // 3. Setup GitHub Action if requested
    if (setupAction) {
      const generator = new ActionsGenerator();
      const actionYaml = generator.generate({
        frequency: frequency || "weekly",
        aiProvider: profileData?.aiProvider || "gemini",
      });

      let actionSha: string | undefined;
      const actionPath = ".github/workflows/update-profile.yml";
      
      try {
        const { data: currentAction } = await octokit.rest.repos.getContent({
          owner: username,
          repo: repoName,
          path: actionPath,
        });
        if (!Array.isArray(currentAction)) {
          actionSha = currentAction.sha;
        }
      } catch (e) {
        // Doesn't exist
      }

      await octokit.rest.repos.createOrUpdateFileContents({
        owner: username,
        repo: repoName,
        path: actionPath,
        message: "🤖 Setup ProfileAgent auto-update workflow",
        content: Buffer.from(actionYaml).toString("base64"),
        sha: actionSha,
      });
    }

    return NextResponse.json({
      success: true,
      url: `https://github.com/${username}/${repoName}`,
    });
  } catch (error) {
    const err = error as Error;
    console.error("Deployment error:", err);
    return NextResponse.json(
      { success: false, error: err.message || "Failed to deploy to GitHub" },
      { status: 500 }
    );
  }
}
